// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.22.3
// source: grpc/cashdesk/cashdesk.proto

package cashdeskpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamWorkstationEventsResponse_EVENT_TYPE int32

const (
	StreamWorkstationEventsResponse_PURCHASE    StreamWorkstationEventsResponse_EVENT_TYPE = 0
	StreamWorkstationEventsResponse_CLOSE_SHIFT StreamWorkstationEventsResponse_EVENT_TYPE = 1
)

// Enum value maps for StreamWorkstationEventsResponse_EVENT_TYPE.
var (
	StreamWorkstationEventsResponse_EVENT_TYPE_name = map[int32]string{
		0: "PURCHASE",
		1: "CLOSE_SHIFT",
	}
	StreamWorkstationEventsResponse_EVENT_TYPE_value = map[string]int32{
		"PURCHASE":    0,
		"CLOSE_SHIFT": 1,
	}
)

func (x StreamWorkstationEventsResponse_EVENT_TYPE) Enum() *StreamWorkstationEventsResponse_EVENT_TYPE {
	p := new(StreamWorkstationEventsResponse_EVENT_TYPE)
	*p = x
	return p
}

func (x StreamWorkstationEventsResponse_EVENT_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamWorkstationEventsResponse_EVENT_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_cashdesk_cashdesk_proto_enumTypes[0].Descriptor()
}

func (StreamWorkstationEventsResponse_EVENT_TYPE) Type() protoreflect.EnumType {
	return &file_grpc_cashdesk_cashdesk_proto_enumTypes[0]
}

func (x StreamWorkstationEventsResponse_EVENT_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamWorkstationEventsResponse_EVENT_TYPE.Descriptor instead.
func (StreamWorkstationEventsResponse_EVENT_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_grpc_cashdesk_cashdesk_proto_rawDescGZIP(), []int{1, 0}
}

type StreamWorkstationEventsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorkstationId string `protobuf:"bytes,1,opt,name=workstation_id,json=workstationId,proto3" json:"workstation_id,omitempty"`
}

func (x *StreamWorkstationEventsRequest) Reset() {
	*x = StreamWorkstationEventsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_cashdesk_cashdesk_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamWorkstationEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamWorkstationEventsRequest) ProtoMessage() {}

func (x *StreamWorkstationEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_cashdesk_cashdesk_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamWorkstationEventsRequest.ProtoReflect.Descriptor instead.
func (*StreamWorkstationEventsRequest) Descriptor() ([]byte, []int) {
	return file_grpc_cashdesk_cashdesk_proto_rawDescGZIP(), []int{0}
}

func (x *StreamWorkstationEventsRequest) GetWorkstationId() string {
	if x != nil {
		return x.WorkstationId
	}
	return ""
}

type StreamWorkstationEventsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventType StreamWorkstationEventsResponse_EVENT_TYPE `protobuf:"varint,1,opt,name=event_type,json=eventType,proto3,enum=net.vseinstrumenti.git.fd.proto.cashdesk.StreamWorkstationEventsResponse_EVENT_TYPE" json:"event_type,omitempty"`
}

func (x *StreamWorkstationEventsResponse) Reset() {
	*x = StreamWorkstationEventsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_cashdesk_cashdesk_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamWorkstationEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamWorkstationEventsResponse) ProtoMessage() {}

func (x *StreamWorkstationEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_cashdesk_cashdesk_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamWorkstationEventsResponse.ProtoReflect.Descriptor instead.
func (*StreamWorkstationEventsResponse) Descriptor() ([]byte, []int) {
	return file_grpc_cashdesk_cashdesk_proto_rawDescGZIP(), []int{1}
}

func (x *StreamWorkstationEventsResponse) GetEventType() StreamWorkstationEventsResponse_EVENT_TYPE {
	if x != nil {
		return x.EventType
	}
	return StreamWorkstationEventsResponse_PURCHASE
}

var File_grpc_cashdesk_cashdesk_proto protoreflect.FileDescriptor

var file_grpc_cashdesk_cashdesk_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x63, 0x61, 0x73, 0x68, 0x64, 0x65, 0x73, 0x6b, 0x2f,
	0x63, 0x61, 0x73, 0x68, 0x64, 0x65, 0x73, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x28,
	0x6e, 0x65, 0x74, 0x2e, 0x76, 0x73, 0x65, 0x69, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x6d, 0x65, 0x6e,
	0x74, 0x69, 0x2e, 0x67, 0x69, 0x74, 0x2e, 0x66, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x63, 0x61, 0x73, 0x68, 0x64, 0x65, 0x73, 0x6b, 0x22, 0x47, 0x0a, 0x1e, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x57, 0x6f, 0x72, 0x6b, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x77, 0x6f,
	0x72, 0x6b, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0d, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49,
	0x64, 0x22, 0xc3, 0x01, 0x0a, 0x1f, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x57, 0x6f, 0x72, 0x6b,
	0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x73, 0x0a, 0x0a, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x54, 0x2e, 0x6e, 0x65, 0x74, 0x2e,
	0x76, 0x73, 0x65, 0x69, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x69, 0x2e, 0x67,
	0x69, 0x74, 0x2e, 0x66, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x61, 0x73, 0x68,
	0x64, 0x65, 0x73, 0x6b, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x57, 0x6f, 0x72, 0x6b, 0x73,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x52,
	0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x22, 0x2b, 0x0a, 0x0a, 0x45, 0x56,
	0x45, 0x4e, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x12, 0x0c, 0x0a, 0x08, 0x50, 0x55, 0x52, 0x43,
	0x48, 0x41, 0x53, 0x45, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x4c, 0x4f, 0x53, 0x45, 0x5f,
	0x53, 0x48, 0x49, 0x46, 0x54, 0x10, 0x01, 0x32, 0xbf, 0x01, 0x0a, 0x08, 0x43, 0x61, 0x73, 0x68,
	0x64, 0x65, 0x73, 0x6b, 0x12, 0xb2, 0x01, 0x0a, 0x17, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x57,
	0x6f, 0x72, 0x6b, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73,
	0x12, 0x48, 0x2e, 0x6e, 0x65, 0x74, 0x2e, 0x76, 0x73, 0x65, 0x69, 0x6e, 0x73, 0x74, 0x72, 0x75,
	0x6d, 0x65, 0x6e, 0x74, 0x69, 0x2e, 0x67, 0x69, 0x74, 0x2e, 0x66, 0x64, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x63, 0x61, 0x73, 0x68, 0x64, 0x65, 0x73, 0x6b, 0x2e, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x57, 0x6f, 0x72, 0x6b, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x49, 0x2e, 0x6e, 0x65, 0x74,
	0x2e, 0x76, 0x73, 0x65, 0x69, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x69, 0x2e,
	0x67, 0x69, 0x74, 0x2e, 0x66, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x61, 0x73,
	0x68, 0x64, 0x65, 0x73, 0x6b, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x57, 0x6f, 0x72, 0x6b,
	0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x42, 0x3d, 0x5a, 0x3b, 0x67, 0x69, 0x74,
	0x2e, 0x76, 0x73, 0x65, 0x69, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x69, 0x2e,
	0x6e, 0x65, 0x74, 0x2f, 0x66, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x72, 0x70,
	0x63, 0x2f, 0x63, 0x61, 0x73, 0x68, 0x64, 0x65, 0x73, 0x6b, 0x2f, 0x67, 0x6f, 0x2f, 0x63, 0x61,
	0x73, 0x68, 0x64, 0x65, 0x73, 0x6b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_cashdesk_cashdesk_proto_rawDescOnce sync.Once
	file_grpc_cashdesk_cashdesk_proto_rawDescData = file_grpc_cashdesk_cashdesk_proto_rawDesc
)

func file_grpc_cashdesk_cashdesk_proto_rawDescGZIP() []byte {
	file_grpc_cashdesk_cashdesk_proto_rawDescOnce.Do(func() {
		file_grpc_cashdesk_cashdesk_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_cashdesk_cashdesk_proto_rawDescData)
	})
	return file_grpc_cashdesk_cashdesk_proto_rawDescData
}

var file_grpc_cashdesk_cashdesk_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_grpc_cashdesk_cashdesk_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grpc_cashdesk_cashdesk_proto_goTypes = []interface{}{
	(StreamWorkstationEventsResponse_EVENT_TYPE)(0), // 0: net.vseinstrumenti.git.fd.proto.cashdesk.StreamWorkstationEventsResponse.EVENT_TYPE
	(*StreamWorkstationEventsRequest)(nil),          // 1: net.vseinstrumenti.git.fd.proto.cashdesk.StreamWorkstationEventsRequest
	(*StreamWorkstationEventsResponse)(nil),         // 2: net.vseinstrumenti.git.fd.proto.cashdesk.StreamWorkstationEventsResponse
}
var file_grpc_cashdesk_cashdesk_proto_depIdxs = []int32{
	0, // 0: net.vseinstrumenti.git.fd.proto.cashdesk.StreamWorkstationEventsResponse.event_type:type_name -> net.vseinstrumenti.git.fd.proto.cashdesk.StreamWorkstationEventsResponse.EVENT_TYPE
	1, // 1: net.vseinstrumenti.git.fd.proto.cashdesk.Cashdesk.StreamWorkstationEvents:input_type -> net.vseinstrumenti.git.fd.proto.cashdesk.StreamWorkstationEventsRequest
	2, // 2: net.vseinstrumenti.git.fd.proto.cashdesk.Cashdesk.StreamWorkstationEvents:output_type -> net.vseinstrumenti.git.fd.proto.cashdesk.StreamWorkstationEventsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_grpc_cashdesk_cashdesk_proto_init() }
func file_grpc_cashdesk_cashdesk_proto_init() {
	if File_grpc_cashdesk_cashdesk_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_cashdesk_cashdesk_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamWorkstationEventsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_cashdesk_cashdesk_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamWorkstationEventsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_cashdesk_cashdesk_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_cashdesk_cashdesk_proto_goTypes,
		DependencyIndexes: file_grpc_cashdesk_cashdesk_proto_depIdxs,
		EnumInfos:         file_grpc_cashdesk_cashdesk_proto_enumTypes,
		MessageInfos:      file_grpc_cashdesk_cashdesk_proto_msgTypes,
	}.Build()
	File_grpc_cashdesk_cashdesk_proto = out.File
	file_grpc_cashdesk_cashdesk_proto_rawDesc = nil
	file_grpc_cashdesk_cashdesk_proto_goTypes = nil
	file_grpc_cashdesk_cashdesk_proto_depIdxs = nil
}
